variables:
  DOCKER_IMAGE: '$IMAGE_URL'
image: '$DOCKER_IMAGE'
stages:
  - lint
  - validate
  - deploy
  - release

lint:composer:
  stage: lint
  script:
    - composer validate --no-interaction --strict
  tags:
    - k8s-tbk

lint:secretsscan:
  image: '$IMAGE_URL_PYTHON'
  stage: lint
  script:
    - ci/scan_secrets.sh
  tags:
    - k8s-tbk

validate:tag-message:
  stage: validate
  only:
    - tags
  script:
    - ci/validate_tag_message.sh $CI_COMMIT_TAG
  tags:
    - k8s-tbk

deploy:deploy-to-github:
  stage: deploy
  only:
    - tags
  script:
    - ci/deploy_to_github.sh
  tags:
    - k8s-tbk

release:release-to-github:
  image: '$IMAGE_URL_PYTHON'
  stage: release
  only:
    - tags
  script:
    - ci/release_to_github.sh $CI_COMMIT_TAG
  tags:
    - k8s-tbk
