parameters: {}

services:
  # Initiate Factory
  Transip\Bundle\RestApi\Factory\TransipApiClientFactory:
    arguments:
      $clientBuilder: '@transip.client.http'
      $cache: '@Symfony\Component\Cache\Adapter\AdapterInterface'

  # Register TransIP API class
  Transip\Api\Library\TransipAPI:
    factory: ['@Transip\Bundle\RestApi\Factory\TransipApiClientFactory', 'createApiClient']
